services:
  pl-nginx:
    image: nginx
    container_name: 'pl-nginx'
    depends_on:
      - pl-php-fpm
    ports:
      - '18080:80'
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx:delegated

  pl-php-fpm:
    build: docker
    container_name: 'pl-php-fpm'
    restart: unless-stopped
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      XDEBUG_MODE: 'debug'
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_TRIGGER: 'yes'

  pl-postgres:
    image: postgres:15
    ports:
      - 15432:5432
    container_name: 'pl-postgresql'
    restart: always
    environment:
      POSTGRES_DB: 'pl_db'
      POSTGRES_USER: 'pl_db_user'
      POSTGRES_PASSWORD: 'pl_db_password'
    volumes:
      - pl_dump:/app/dump
      - pl_postgresql:/var/lib/postgresql/data

volumes:
  pl_dump:
  pl_postgresql:
