controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api:
    resource:
        path: ../src/Infrastructure/Delivery/Api/
        namespace: App\Infrastructure\Delivery\Api
    type: attribute
